export const INIT_LOADING = 'INIT_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';
export const SET_LAST_MOVES = 'SET_LAST_MOVES';
export const SET_LAST_WINNER = 'SET_LAST_WINNER';
export const INCREASE_CPU_WINS = 'INCREASE_CPU_WINS';
export const INCREASE_PLAYER_WINS = 'INCREASE_PLAYER_WINS';
